/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: process.env.DARK_MODE ? process.env.DARK_MODE : 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './lib/**/*.{js,jsx,ts,tsx}',
    './*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  important: 'html',
  safelist: [
    {
      pattern:
        /(bg|border|text|stroke|fill)-(background|foreground|card|card-foreground|popover|popover-foreground|primary|primary-foreground|secondary|secondary-foreground|muted|muted-foreground|accent|accent-foreground|destructive|border|input|ring|chart-1|chart-2|chart-3|chart-4|chart-5|sidebar|sidebar-foreground|sidebar-primary|sidebar-primary-foreground|sidebar-accent|sidebar-accent-foreground|sidebar-border|sidebar-ring)/,
    },
  ],
  theme: {
    extend: {
      borderRadius: {
        DEFAULT: 'var(--radius)',
        lg: 'calc(var(--radius) * 1.5)',
        md: 'var(--radius)',
        sm: 'calc(var(--radius) * 0.5)',
      },
      colors: {
        // ── Legacy SN aliases → resolve via CSS vars so stray legacy classes
        //    stay dark-mode correct (back-compat only; new screens use shadcn) ──
        bg: 'rgb(var(--background) / <alpha-value>)',
        fg: 'rgb(var(--foreground) / <alpha-value>)',
        surface: 'rgb(var(--card) / <alpha-value>)',
        'surface-high': 'rgb(var(--muted) / <alpha-value>)',
        subtle: 'rgb(var(--muted-foreground) / <alpha-value>)',
        'accent-soft': 'rgb(var(--muted) / <alpha-value>)',
        'accent-fg': 'rgb(var(--accent-foreground) / <alpha-value>)',
        divider: 'rgb(var(--border) / <alpha-value>)',
        success: '#10B981', 'success-soft': '#D1FAE5',
        danger: '#EF4444', 'danger-soft': '#FEE2E2',
        warning: '#F59E0B', 'warning-soft': '#FEF3C7',
        // ── shadcn semantic tokens via CSS vars (driven by ThemeProvider) ──
        background: 'rgb(var(--background) / <alpha-value>)',
        foreground: 'rgb(var(--foreground) / <alpha-value>)',
        card: {
          DEFAULT: 'rgb(var(--card) / <alpha-value>)',
          foreground: 'rgb(var(--card-foreground) / <alpha-value>)',
        },
        popover: {
          DEFAULT: 'rgb(var(--popover) / <alpha-value>)',
          foreground: 'rgb(var(--popover-foreground) / <alpha-value>)',
        },
        primary: {
          DEFAULT: 'rgb(var(--primary) / <alpha-value>)',
          foreground: 'rgb(var(--primary-foreground) / <alpha-value>)',
        },
        secondary: {
          DEFAULT: 'rgb(var(--secondary) / <alpha-value>)',
          foreground: 'rgb(var(--secondary-foreground) / <alpha-value>)',
        },
        muted: {
          DEFAULT: 'rgb(var(--muted) / <alpha-value>)',
          foreground: 'rgb(var(--muted-foreground) / <alpha-value>)',
        },
        accent: {
          DEFAULT: 'rgb(var(--accent) / <alpha-value>)',
          foreground: 'rgb(var(--accent-foreground) / <alpha-value>)',
        },
        destructive: { DEFAULT: 'rgb(var(--destructive) / <alpha-value>)' },
        border: 'rgb(var(--border) / <alpha-value>)',
        input: 'rgb(var(--input) / <alpha-value>)',
        ring: 'rgb(var(--ring) / <alpha-value>)',
        chart: {
          1: 'rgb(var(--chart-1) / <alpha-value>)',
          2: 'rgb(var(--chart-2) / <alpha-value>)',
          3: 'rgb(var(--chart-3) / <alpha-value>)',
          4: 'rgb(var(--chart-4) / <alpha-value>)',
          5: 'rgb(var(--chart-5) / <alpha-value>)',
        },
        sidebar: {
          'DEFAULT': 'rgb(var(--sidebar) / <alpha-value>)',
          'foreground': 'rgb(var(--sidebar-foreground) / <alpha-value>)',
          'primary': 'rgb(var(--sidebar-primary) / <alpha-value>)',
          'primary-foreground': 'rgb(var(--sidebar-primary-foreground) / <alpha-value>)',
          'accent': 'rgb(var(--sidebar-accent) / <alpha-value>)',
          'accent-foreground': 'rgb(var(--sidebar-accent-foreground) / <alpha-value>)',
          'border': 'rgb(var(--sidebar-border) / <alpha-value>)',
          'ring': 'rgb(var(--sidebar-ring) / <alpha-value>)',
        },
      },
      fontFamily: {
        'heading': ['Inter_600SemiBold'],
        'heading-bold': ['Inter_700Bold'],
        'body': ['Inter_400Regular'],
        'body-medium': ['Inter_500Medium'],
        'mono': ['JetBrainsMono_400Regular'],
        'mono-medium': ['JetBrainsMono_500Medium'],
        'inter': ['Inter_400Regular'],
        'inter-medium': ['Inter_500Medium'],
        'inter-semibold': ['Inter_600SemiBold'],
        'inter-bold': ['Inter_700Bold'],
        'jetbrains': ['JetBrainsMono_400Regular'],
        'jetbrains-medium': ['JetBrainsMono_500Medium'],
      },
      fontWeight: { extrablack: '950' },
      fontSize: {
        '2xs':     ['10px'],
        display:   ['34px', { lineHeight: '40px', letterSpacing: '-1px',   fontWeight: '800' }],
        title1:    ['28px', { lineHeight: '34px', letterSpacing: '-0.5px', fontWeight: '700' }],
        title2:    ['22px', { lineHeight: '28px', letterSpacing: '-0.3px', fontWeight: '700' }],
        title3:    ['20px', { lineHeight: '26px', letterSpacing: '-0.2px', fontWeight: '600' }],
        headline:  ['17px', { lineHeight: '24px', letterSpacing: '-0.1px', fontWeight: '600' }],
        body:      ['17px', { lineHeight: '26px', letterSpacing: '0',      fontWeight: '400' }],
        callout:   ['16px', { lineHeight: '24px', letterSpacing: '0',      fontWeight: '400' }],
        subhead:   ['15px', { lineHeight: '22px', letterSpacing: '0',      fontWeight: '500' }],
        footnote:  ['13px', { lineHeight: '20px', letterSpacing: '0.1px',  fontWeight: '400' }],
        caption:   ['12px', { lineHeight: '18px', letterSpacing: '0.2px',  fontWeight: '400' }],
        caption2:  ['11px', { lineHeight: '16px', letterSpacing: '0.3px',  fontWeight: '400' }],
      },
      boxShadow: {
        'hard-1': '-2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-2': '0px 3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-3': '2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-4': '0px -3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-5': '0px 2px 10px 0px rgba(38, 38, 38, 0.10)',
        'soft-1': '0px 0px 10px rgba(38, 38, 38, 0.1)',
        'soft-2': '0px 0px 20px rgba(38, 38, 38, 0.2)',
        'soft-3': '0px 0px 30px rgba(38, 38, 38, 0.1)',
        'soft-4': '0px 0px 40px rgba(38, 38, 38, 0.1)',
      },
    },
  },
  plugins: [],
};
