begin;

-- Film Festival OS™
-- Migration 066
-- Preserve the verified jury/workflow audit-event insert policy.
--
-- Required so authenticated ACTIVE members of the same tenant can
-- create controlled audit events generated by permitted FFOS workflows.

drop policy if exists audit_events_insert_active_member
on public.audit_events;

create policy audit_events_insert_active_member
on public.audit_events
for insert
to authenticated
with check (
  exists (
    select 1
    from public.memberships m
    where m.user_id = auth.uid()
      and m.tenant_id = audit_events.tenant_id
      and m.status = 'active'
  )
);

notify pgrst, 'reload schema';

commit;
